### PR TITLE
Prepare Windows builds for newer boosts - Partial back-port of 10175

### PR DESCRIPTION
**Pull request by Wedge009**
Also related to #10657.

I don't really know what I'm doing but I found to get Windows/vcpkg compilation working for 1.18 again I had to make these changes. I just haven't committed an update to the vcpkg base-line here because @Vultraz says that needs to wait until the vcpkg GitHub action runner picks up the necessary commit.

I didn't include boost-process in the SCons, Docker, and flatpak scripts because I'm guessing they will stay with older boosts. It's only vcpkg that I expect will pull in boost 1.89 with the updated base-line.

### CODE REVIEW

**Comment by Wedge009** [comment]
Marking as draft until the requisite vcpkg base-line update is available.

**Comment by Wedge009** [comment]
Okay, I suppose the other builds need boost-process too.

**Comment by soliton-** [comment]
What problem is this solving?

**Comment by Wedge009** [comment]
#10657 requires an update to the vcpkg base-line, but as best as I can tell that also means a newer boost - boost 1.89 to be precise. To get 1.18 to compile on MSVC I had to make these changes. I think I'll have to copy what master does with `CMakeLists.txt` because clearly the additional requirement of boost-process isn't working nicely with other platforms.

**Comment by Wedge009** [comment]
Reported and deleted spam content.

**Comment by alexafav-hub** [comment]
https://lo4dgames.org/age-of-empires-series/
Нажмите на эту ссылку, xxx зарабатывайте бесплатно
https://lo4dgames.org/efootball-pes/
Сексуальное полное видео по ссылке

**Comment by soliton-** [comment]
> #10657 requires an update to the vcpkg base-line, but as best as I can tell that also means a newer boost - boost 1.89 to be precise. To get 1.18 to compile on MSVC I had to make these changes.

What were the errors? 1.18 was updated to handle newer boost with ce4f4077494e51ce95d5061582e1be53967d1a07.

**Comment by Wedge009** [comment]
The same as what is showing in the failing 1.18 CI builds on GitHub: vcpkg cannot properly download and build the pango dependency.

When I advance vcpkg to allow pango to build, boost then causes complications. I can't remember the exact failures, and I did see that 1.18 had some differences to master with the commit you cited, but it wasn't sufficient to allow it to build properly.

Edit: I understand that commit was to resolve #10190, which was for non-Windows builds.

**Comment by soliton-** [comment]
The commit was for new boost versions where the API was changed. If there is a windows specific issue then whatever that is needs to be fixed. It seems very unlikely that this involves switching to boost process v2. If that truely is a requirement then it does not seem suitable for 1.18.

**Comment by Wedge009** [comment]
> What were the errors? 1.18 was updated to handle newer boost with [ce4f407](https://github.com/wesnoth/wesnoth/commit/ce4f4077494e51ce95d5061582e1be53967d1a07).

See #10785 which (at the moment) only has vcpkg updates. It is using boost 1.89 which appears to drop a Windows header:
`fatal error C1083: Cannot open include file: 'boost/process/windows.hpp': No such file or directory`

**Comment by Wedge009** [comment]
It may be the case that not everything I've done here is necessary to get 1.18 Windows build working, but definitely something will need to be done in addition to just updating `vcpkg.json` as demonstrated by the build failure in #10785.

**Comment by soliton-** [comment]
If @Vultraz approval is serious then it should contain an explanation on why. Just in case it's not clear I do not approve.

**Comment by Wedge009** [comment]
It might help to clarify why you do not approve or offer some alternative options. Is it possible to replace the use of `boost/process/windows.hpp` while remaining on boost-process V1?

**Comment by Vultraz** [comment]
Since this is confirmed to get the CI working again, and we haven’t had any issues with process v2 on master, and since the backport is fairly small, I don’t see why we need force v1 only for 1.18 if we’re going to continue allow building it with latest Boost. We could also pin an earlier version (1.86 or 1.85) in the vcpkg manifest and make that the last compatible Boost version for 1.18, but that seems like overkill.

**Comment by Wedge009** [comment]
Assuming checks for #10785 pass after the header update, we can merge that one and close this one.

**Comment by Vultraz** [comment]
Alright, looks good to me.
