### ISSUE TITLE
Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [wesnoth/wesnoth#3646]
After boostorg/logic@23cd89d4c80f build fails. See [error log](https://ptpb.pw/eWc1).
```c++
src/units/frame.cpp:463:53: error: no viable conversion from 'const boost::tribool' to 'bool'
                v.emplace_back("auto_vflip=" + utils::bool_string(auto_vflip_));
                                                                  ^~~~~~~~~~~
src/serialization/string_utils.hpp:282:36: note: passing argument to parameter 'value' here
std::string bool_string(const bool value);
                                   ^
src/units/frame.cpp:467:53: error: no viable conversion from 'const boost::tribool' to 'bool'
                v.emplace_back("auto_hflip=" + utils::bool_string(auto_hflip_));
                                                                  ^~~~~~~~~~~
src/serialization/string_utils.hpp:282:36: note: passing argument to parameter 'value' here
std::string bool_string(const bool value);
                                   ^
src/units/frame.cpp:471:56: error: no viable conversion from 'const boost::tribool' to 'bool'
                v.emplace_back("primary_frame=" + utils::bool_string(primary_frame_));
                                                                     ^~~~~~~~~~~~~~
src/serialization/string_utils.hpp:282:36: note: passing argument to parameter 'value' here
std::string bool_string(const bool value);
                                   ^
src/units/frame.cpp:775:13: error: no viable conversion from 'boost::logic::tribool' to 'const bool'
        const bool primary = result.primary_frame == true || boost::logic::indeterminate(result.primary_frame);
                   ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by GregoryLundberg** [comment]
Marking for 1.15 but postponed until Boost 1.69 releases.

Marked Upstream Bug because this really is because Boost is dumb but, as usual, we can work around their stupidity. Should be an easy fix so I'm marking Good First Issue if someone with only basic knowledge of C++ wants to fix it. A quick search on Source Forge should give you enough information to proceed.

**Comment by Wedge009** [comment]
Commenting here to remind myself to check this when boost 1.69 releases.

**Comment by sevu** [comment]
Boost 1.69 just went into the beta phase, I expect the official release to be in the beginning of December.

If it still is a problem … would someone like to make a bugreport upstream?

Marking as blocker, it would be bad to release in case the problem remains.

**Comment by Wedge009** [comment]
boost 1.69 released, confirming that compilation breaks.

I worked around this by adding #define BOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS just before the #inclusion of the boost tribool header in [frame.hpp](https://github.com/wesnoth/wesnoth/blob/master/src/units/frame.hpp#L28). However, I'm not sure that this is the 'right' way to resolve this as this just returns the tribool header to its pre-1.69 state.

**Comment by GregoryLundberg** [comment]
The "right" way usually is to fix the program: in this case, figure out why we're running afoul of the explicit conversion operators for tri-bools, and stop doing that.

There is nothing at all wrong with using a compile-time option to work around the issue. There might be  a better place to do it.

I'd suggest taking a day or three to see if you can fix the code then, if you still want to use the option, be sure to open a ticket and mark the option with a TODO referencing that (this?) ticket. That way it'll end up on the "we should fix this someday" list and it'll be easier to find the background discussion.

**Comment by jostephd** [comment]
Fortunately we don't use tribool that much. I think those four instances might be the only ones, but I don't have boost 1.69 to test. Could someone test this patch with boost 1.69?

```
diff --git a/src/units/frame.cpp b/src/units/frame.cpp
index 3215fa4fa79..06b09c4e39a 100644
--- a/src/units/frame.cpp
+++ b/src/units/frame.cpp
@@ -460,15 +460,15 @@ std::vector<std::string> frame_parsed_parameters::debug_strings() const
 	}
 
 	if(!boost::indeterminate(auto_vflip_)) {
-		v.emplace_back("auto_vflip=" + utils::bool_string(auto_vflip_));
+		v.emplace_back("auto_vflip=" + utils::bool_string(static_cast<bool>(auto_vflip_)));
 	}
 
 	if(!boost::indeterminate(auto_hflip_)) {
-		v.emplace_back("auto_hflip=" + utils::bool_string(auto_hflip_));
+		v.emplace_back("auto_hflip=" + utils::bool_string(static_cast<bool>(auto_hflip_)));
 	}
 
 	if(!boost::indeterminate(primary_frame_)) {
-		v.emplace_back("primary_frame=" + utils::bool_string(primary_frame_));
+		v.emplace_back("primary_frame=" + utils::bool_string(static_cast<bool>(primary_frame_)));
 	}
 
 	if(!drawing_layer_.get_original().empty()) {
@@ -768,7 +768,7 @@ const frame_parameters unit_frame::merge_parameters(int current_time, const fram
 	}
 
 	// Convert the tribool to bool
-	const bool primary = result.primary_frame == true || boost::logic::indeterminate(result.primary_frame);
+	const bool primary = result.primary_frame || boost::logic::indeterminate(result.primary_frame);
 
 	/** The engine provides a default image to use for the unit when none is available */
 	result.image = current_val.image.is_void() || current_val.image.get_filename().empty()
```

**Comment by Wedge009** [comment]
Thanks for the Christmas present / suggestions. I followed what @gfgtdf and @jostephd wrote and the only change I had to make was to static_cast result.primary_frame to bool as well, for the first condition of the last line replacement. If this is acceptable, shall I push this to 1.14 and master?

**Comment by jostephd** [comment]
Yes, please.
