### PR TITLE
Implementation of a "Surrender Game" feature 

### PR DESCRIPTION
**Pull request by kallaballa**
I implemented a "Surrender Game" feature which resides in the in-game main menu. When clicked it opens a confirmation dialog. On confirmation it records a surrender command in all parties replays and the issuing player quits the game.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Replaces #2215

**Comment by Vultraz** [comment]
I don't think the whole `surrender_confirmation` class is necessary at all. The action should simply invoke a modal prompt like what `surrender_confirmation::show_prompt` now does. You've based the class off the `quit_confirmation` class, but that's designed in order to allow multiple "layers" of quit confirmation. It's not the general UI paradigm. It doesn't really make much sense to have multiple 'Do you want to surrender' prompts. :P

**Comment by kallaballa** [comment]
I simplified the dialog implementation and additionally made surrender an undoable command

**Comment by kallaballa** [comment]
My local tests show it works now as expected

File: src/server/game.cpp [hunk 1]
```diff
@@ -867,6 +867,15 @@ bool game::is_legal_command(const simple_wml::node& command, const socket_ptr us
 	if (!command.one_child()) return false;
 	// Chatting is never an illegal command.
 	if (command.child("speak")) return true;
+	if (command.child("surrender")) {
+		const simple_wml::string_span& sn = command.child("surrender")->attr("side_number");
+		if(sn.is_null() || sides_[sn.to_int()] != user) {
```
Comment (soliton-) [inline src/server/game.cpp]: Better change the key from side_number to from_side which already gets checked here. Otherwise you need to check that sn.to_int() is between 0 and sides_.size() - 1 before accessing sides_.

**Comment by kallaballa** [comment]
I can't use from_side because it's a different attribute. so i implemented a bounds check for side_number

**Comment by soliton-** [comment]
What do you mean you can't rename side_number to from_side? You implemented a new surrender tag with whatever attribute names you like. Is there some other code that restricts what you can name your attributes?

**Comment by kallaballa** [comment]
When i use "from_side" it somehow gets filtered or lost. Indeed that attribute seems to be special but i couldn't find the code responsible by now.

**Comment by Vultraz** [comment]
Indeed, “from_side” is a key used elsewhere.

Btw, I think you should drop the ‘surrender_confirmation’ class altogether and just combine it’s two functions into one member in ‘command_executor’.

**Comment by kallaballa** [comment]
dropped class surrender_confirmation in favor of a function in command_executor

**Comment by gfgtdf** [comment]
Iirc you also wanted to replace the 'are you sure you want to quit' dialog with a '[quit without surrendering], [surrnder and quit], [don't quit]' dialog, i don't see that in this pr, do you still intend to do that?

I'm unsure whether it does make sense to have to available in sp scenarios too, currently i'd say it'd be better if it was a available only in mp.

**Comment by kallaballa** [comment]
Nope.. never planned to do that. How can make it unavailable in SP scenarios?

**Comment by gfgtdf** [comment]
> Nope.. never planned to do that.

Hmm thne i now officially suggest that feature (doesn't mean you ahve to do it)

> How can make it unavailable in SP scenarios?

Currently `play_controller::hotkey_handler::can_execute_command` returns always true for `hotkey::HOTKEY_SURRENDER_GAME`, you coudl change that code, but what woudl be better if to move that decision check to `playmp_controller::hotkey_handler::can_execute_command` (src/hotkey/hotkey_handler_mp.cpp)  and remove the code in `play_controller::hotkey_handler::can_execute_command`. also it'd be nice if this surrendering was disabled if the game already ended (if it is in linger mode)

**Comment by gfgtdf** [comment]
oh and of course the surrender option only makes sense if the player actually controls a side (is not an observer), maybe a check for that shodul be added too in can_execute_command .

also it might not make sense to surrender if you have already surrendered but i think this is  minor one.

Your code  `pmc->surrender(resources::controller->current_side());` seems to surrender for the side that has the current turn. But you probably want the side that is contrlooled by the local client (that is `controller::gui_->viewing_side()` i think )

**Comment by kallaballa** [comment]
Thx for the input! done.

**Comment by gfgtdf** [comment]
looks good to me, unless you want to implement the quit-or-surrender dialog or do some code cleanups we can merge this.

**Comment by kallaballa** [comment]
you are right - it breaks. gonna fix. i'm not sure if i should do the  quit-or-surrender dialog simply because i don't have enough opinions on that. i'll ask some seasoned players.

**Comment by kallaballa** [comment]
Ok.. i'll implement the quit-or-surrender dialog. people are in favor of it, it seems

File: src/hotkey/hotkey_handler_mp.cpp [hunk 2]
```diff
@@ -71,7 +71,10 @@ bool playmp_controller::hotkey_handler::can_execute_command(const hotkey::hotkey
 		case hotkey::HOTKEY_STOP_NETWORK:
 			res = is_observer();
 			break;
-	    default:
+		case hotkey::HOTKEY_SURRENDER_GAME:
+			res = !(playmp_controller_.is_linger_mode() || playmp_controller_.is_observer());
+			break;
+			default:
```
Comment (GregoryLundberg) [inline src/hotkey/hotkey_handler_mp.cpp]: Check indentation.

File: src/server/game.cpp [hunk 3]
```diff
@@ -867,6 +867,20 @@ bool game::is_legal_command(const simple_wml::node& command, const socket_ptr us
...
 	// Chatting is never an illegal command.
 	if (command.child("speak")) return true;
+	if (command.child("surrender")) {
+		const simple_wml::string_span& sn = command.child("surrender")->attr("side_number");
+		if(sn.is_null())
+			return false;
+
+		int side_number = sn.to_int();
+
+		if(sn.is_null() || side_number < 0 || ((size_t)side_number) >= sides_.size() || sides_[sn.to_int()] != user) {
```
Comment (GregoryLundberg) [inline src/server/game.cpp]: use static_cast<size_t> here
why call sn.to_int() again, juse use side_number

**Comment by GregoryLundberg** [comment]
Some sequencing issues.

Testing with 3 terminals. (1) running wesnothd (2) starts 2p athermaw (3) joins athermaw

Terminal 2 starts the game it created and is waiting during the initial [start] messages.

Terminal 3 surrenders before its first turn

Terminal 2 clears messages to begin play and sees query dialog about other player having left and do you want another player or an AI to fill in.

On-screen messages for terminal 2 read something about <server> removing unknown command 'surrender'

**Comment by kallaballa** [comment]
I impemented the quit_or_surrender and i fixed the c cast as well as the indentation. Sequencing issue still unresolved.

**Comment by kallaballa** [comment]
I found the problem that caused the illegal command message. i used viewing_side instead of viewing_team to get the internal side index.

**Comment by gfgtdf** [comment]
1) .cfg files in the dsata/gui directory should be indented by tabs.

2) your current code seems to just display to 'quit or surrender' dialog when you click quit game, not when you close the application.

3) It'd be better if the surrender_quit_game function was a memeber function of playmp_controller that is the called via hotkey_handler_mp (like for example `playmp_controller::hotkey_handler::stop_network`)

**Comment by kallaballa** [comment]
so you are saying the quit_to_desktop should also have a surrender option?

**Comment by gfgtdf** [comment]
yes, what i suggest is basically in playmp_controller have a code like
```
quit_confirmation::set_prompt([](){
    ....  gui2::dialogs::surrender_quit ....
})

```

**Comment by kallaballa** [comment]
instead of creating a set_prompt function i modified the default_prompt. i think it's more readable having all the quit code in one place. acceptable?

**Comment by gfgtdf** [comment]
hmm i still think it'd be better to have it in playmp_controller instead of using resources::, but it's ok. I can merge it unless someone objects.

**Comment by gfgtdf** [comment]
Maybe someoneelse can merge this? I am on my mobile and won't have access to my main pc for the next 10 days and the github webpage doesn't work properly on this browser.

**Comment by GregoryLundberg** [comment]
rebase and merge by hand

**Comment by Vultraz** [comment]
Reverted merge (e08350c). This needs significantly more consideration when it comes to design.

* The "surrender" command is still flagged as illegal by the server.
* What is the difference between quitting and surrendering and quitting without surrendering? You quit in both cases, and the side is reassigned. Only difference is the Surrender codepath triggers the above warning. Would make more sense that a Surrender feature would demote you to an observer, or something.

**Comment by gfgtdf** [comment]
> The "surrender" command is still flagged as illegal by the server.

And you are sure that you didn't just forgit to rebuild the serever when you tested this?

**Comment by kallaballa** [comment]
Please try again. It works. 
And to be honest, I'm a bit frustrated because this is the third time someone tells me i should do this feature differently and throw away the code i've written. who or what decides how this should be done? Every time i implemented it i did it following the suggestions of a BfW developer and everytime another developer shows up and tells me to do it differently. 
The decision process is f****d.

**Comment by Vultraz** [comment]
I agree, we've screwed up this PR all to hell. I'm sorry :( At this point, I think it best you abandon your effort and let us take it from here. We have your proof of concept to work from, and we'll ensure you get proper credit once we work out some of these details we can't seem to agree on.

**Comment by Vultraz** [comment]
(FTR, @gfgtdf was right about the server error. It simply hadn't been rebuilt)

**Comment by soliton-** [comment]
I think up until the reversion the process went fine. A bit of back and forth between developers to figure out the best way to implement something is normal. That should be similar whether it's a PR from an existing dev or a new contributor.

It's not clear to me at all what the plan now is. I'd like to know though since I'm looking forward to this feature.

**Comment by GregoryLundberg** [comment]
Agreement. I don't see why this PR could not be salvaged. It's just one commit and there is no reason for the small staff we have to take over something a volunteer seems both willing and capable to complete.

**Comment by CelticMinstrel** [comment]
I agree, from what I can tell it sounds like the feature did work, so assuming that's correct I think the reversion should be reverted.

**Comment by kallaballa** [comment]
I'd be willing to continue working on this PR if we can definitely clarify how this feature should work.

**Comment by GregoryLundberg** [comment]
@Vultraz Sounds like it's your call.

**Comment by Vultraz** [comment]
After some discussion I think we've come to an agreement on how Surrendering should work:
* There should be two menu items, Quit and Surrender.
* For Quit, the prompt should have an option to surrender while quitting (like you have here). This should have no effect on the game except to record the side as surrendered in the replay. Either way, the player quits, and the host then gets to decide what to do with the side as normal.
* For plain Surrender, the player cedes control of their side and becomes an observer. The host then gets to decide what to do with the side (droid it, etc) the same as if the player quit.

If you would like to continue working on this feature yourself, feel free, but otherwise I can make the necessary changes myself and re-merge in a day or two. Again, I'm really sorry this became such a mess. It's definitely not a great experience for a new contributor. :(

**Comment by kallaballa** [comment]
Thanks for clarifying. I'll implement it

File: source_lists/wesnoth [hunk 4]
```diff
@@ -247,9 +247,6 @@ gui/dialogs/unit_recruit.cpp
 gui/dialogs/wml_error.cpp
 gui/dialogs/wml_message.cpp
 gui/dialogs/surrender_quit.cpp
-gui/widgets/addon_list.cpp
-gui/widgets/button.cpp
-gui/widgets/chatbox.cpp
```
Comment (GregoryLundberg) [inline source_lists/wesnoth]: Looks like you need to rebase to current master.

Comment (kallaballa) [reply source_lists/wesnoth]: That's the result of merging master. I just re-checked and those files are not in the source list of master

**Comment by kallaballa** [comment]
I have implemented it as requested. It works but i'm not sure i did it in the canonical or simplest way. Please review

**Comment by Pentarctagon** [comment]
I assume the travis and appveyor builds should be succeeding, at least?

**Comment by GregoryLundberg** [comment]
No. Looks like a failure on all CI runs due to compile error in unrelated code. I'm not getting it locally. Most likely a rebase to master will fix it. I'll pull the PR local and take a look just to be sure.

**Comment by GregoryLundberg** [comment]
After a rebase, like the CI runs, I get the following hard errors:

```
/home/lundberg/wesnoth/src/server/game.cpp: In member function ‘bool wesnothd::game::process_turn(simple_wml::document&, socket_ptr)’:
/home/lundberg/wesnoth/src/server/game.cpp:1084:15: error: no match for ‘operator*’ (operand type is ‘simple_wml::node’)
   } else if ((**command).child("surrender")) {
               ^~~~~~~~~
/home/lundberg/wesnoth/src/server/game.cpp:1116:42: error: no match for ‘operator*’ (operand type is ‘simple_wml::node’)
   } else if (is_current_player(user) && (**command).child("end_turn")) {
                                          ^~~~~~~~~
```

**Comment by Vultraz** [comment]
You just need to use `(*command)` or `command->` now, since  I switched that loop to range-for in a recent change on master.

**Comment by GregoryLundberg** [comment]
1) Please use `command->` and never `(*command).`

2) Lots of logic flaws. I tested Aethermaw with 2P+1O 

a) Run 1, side 1 (owner) surrenders. side 2 takes control, observer gets side 1, no choices, nobody can surrender.

b) Run 2, side 2 surrenders and keeps playing, surrenders again and side 1 gets selection of options. "X" closed everyone and had option to surrender on them.

I gave up at that point. This is __SO__ not ready to merge. I'm not quite sure what it's supposed to be doing, but it's obviously missing something.

**Comment by soliton-** [comment]
@kallaballa Please accept my force push. I've rebased your changes properly on master again so we're back on track to get this in.

**Comment by kallaballa** [comment]
sure... but how do you mean? you didn't create a pull request so i'm not sure i understand

**Comment by kallaballa** [comment]
btw... i'm still gonna finish this PR... just don't have the time right now

**Comment by soliton-** [comment]
I was hoping I pushed to this PR but I guess that was not what I did...

**Comment by kallaballa** [comment]
I think you have to create a pull request for: https://github.com/kallaballa/wesnoth/tree/surrender
Than i can accept it and push it to the PR. am i wrong?

**Comment by soliton-** [comment]
Looks like it worked now.

File: src/quit_confirmation.cpp [hunk 5]
```diff
@@ -59,5 +62,26 @@ bool quit_confirmation::show_prompt(const std::string& message)
 
 bool quit_confirmation::default_prompt()
 {
-	return show_prompt(_("Do you really want to quit?"));
+	playmp_controller* pmc = dynamic_cast<playmp_controller*>(resources::controller);
```
Comment (soliton-) [inline src/quit_confirmation.cpp]: It seems to me the only reason you need a playmp_controller is for the surrender() call. I suggest moving the surrender() function to play_controller. I see no reason to limit this to mp even if it might not make too much sense in sp.

Then you can get rid of the ugly dynamic_cast.

File: src/hotkey/command_executor.cpp [hunk 6]
```diff
@@ -362,9 +364,10 @@ bool command_executor::execute_command(const hotkey_command&  cmd, int /*index*/
 
 void command_executor::surrender_game() {
 	if(gui2::show_message(_("Surrender"), _("Do you really want to surrender the game?"), gui2::dialogs::message::yes_no_buttons) != gui2::window::CANCEL) {
-
-	} else {
-
+		playmp_controller* pmc = dynamic_cast<playmp_controller*>(resources::controller);
```
Comment (soliton-) [inline src/hotkey/command_executor.cpp]: Once surrender() is moved to play_controller there is no dynamic_cast need here anymore either.

File: src/hotkey/hotkey_handler.cpp [hunk 7]
```diff
@@ -324,6 +323,16 @@ bool play_controller::hotkey_handler::can_execute_command(const hotkey::hotkey_c
 	case hotkey::HOTKEY_SCROLL_RIGHT:
 		return true;
 
+	case hotkey::HOTKEY_SURRENDER: {
+		size_t humans_notme_cnt = 0;
+		for(const auto& t : play_controller_.get_teams_const()) {
+			if(t.is_human() && !t.is_local()) {
```
Comment (soliton-) [inline src/hotkey/hotkey_handler.cpp]: Could be simplified to is_network_human().

File: src/hotkey/hotkey_handler.cpp [hunk 8]
```diff
@@ -272,6 +272,7 @@ bool play_controller::hotkey_handler::can_execute_command(const hotkey::hotkey_c
 			return true;
 		}
 	}
+	size_t humans_notme_cnt = 0;
```
Comment (GregoryLundberg) [inline src/hotkey/hotkey_handler.cpp]: I am checking out a new tool which says this variable (but not the one below on line 328) is not used.

Verify and remove if this is correct.

Comment (soliton-) [reply src/hotkey/hotkey_handler.cpp]: I had moved the variable into a smaller scope in the case.

Since this PR was turned back into the mess it was before my force push the variable declaration is now duplicated.

Comment (kallaballa) [reply src/hotkey/hotkey_handler.cpp]: i don't understand

Comment (GregoryLundberg) [reply src/hotkey/hotkey_handler.cpp]: Why don't you (@kallaballa) add him (@soliton-) as a contributor on your fork and let him clean up the PR and force-push it?

**Comment by kallaballa** [comment]
@GregoryLundberg 

The behaviour i see: Aethermaw 2P + 1O

1. Player 1 (owner) surrenders. Player 2 gets control. No choice (i don't know how to invoke the choice dialog). No one can surrender anymore, since both sides are in control of player 2

Second scenario i can verify doesn't work as expected

**Comment by kallaballa** [comment]
Second scenario should work now too

**Comment by CelticMinstrel** [comment]
What sort of choice dialog do you want?

**Comment by kallaballa** [comment]
The dialog that ask you what do do with a side

**Comment by CelticMinstrel** [comment]
The one that appears when someone leaves an MP game? (If I recall correctly)

**Comment by kallaballa** [comment]
yes

**Comment by CelticMinstrel** [comment]
Hmm, maybe this could be what you need? 

https://github.com/wesnoth/wesnoth/blob/master/src/gui/dialogs/multiplayer/mp_change_control.hpp

**Comment by soliton-** [comment]
I've force pushed again with the latest tweaks. Also fixed the copyright in the new files.

File: src/server/game.cpp [hunk 9]
```diff
@@ -1071,6 +1071,35 @@ bool game::process_turn(simple_wml::document& data, const socket_ptr user)
...
+				}
+				++sidei;
+			}
+
+			if(sidei < sides_.size()) {
+				simple_wml::document cfg;
+				std::string playername;
+				cfg.root().set_attr("side", std::to_string(sidei + 1).c_str());
+
+				if(owner_ == user) {
```
Comment (soliton-) [inline src/server/game.cpp]: Why is this check necessary? What's the difference to just unconditionally doing "playername = username(user);"?

Comment (kallaballa) [reply src/server/game.cpp]: If you surrender someone needs to take control. This code determines the next side to take control (via transfer_side_control).

**Comment by kallaballa** [comment]
Some the code you pushed wasn't up to date with the latest code i pushed... I need to merge

**Comment by soliton-** [comment]
I keep saying force push so you know that I OVERWROTE your changes. If you then in turn revert that this is all useless. I think I give up and will commit this to master directly once I can figure out the last question I posted.

**Comment by kallaballa** [comment]
well.. you also overwrote bug fixes because you pushed an old version. that's why you had to ask what the check does, because it was out of date and didn't make any sense. i tried to keep your contribution as best as possible. I'm sorry if there is any misunderstanding

**Comment by soliton-** [comment]
No, the fix for that check was in what I pushed. The question remains why the conditional is needed at all.

**Comment by kallaballa** [comment]
the conditional is need because if you surrender someone needs to take control. This code determines the next side to take control (via transfer_side_control).

**Comment by Vultraz** [comment]
I agree with @soliton-

**Comment by soliton-** [comment]
@kallaballa Please do not overwrite/merge/whatever what I've just pushed.

I guess no one explained the PR process so far. This is how I see it anyway:
The idea is that you rewrite your changes until they're ready to be merged into master.
This means amending your commits as I have done and force pushing to rewrite the PR.
In case of bigger, separate changes adding a commit is fine as well, of course. Small corrections should be done by amending existing commits though.

So since I've done the rewriting here and not you/the author, you need to reset your feature branch to the new state.

**Comment by GregoryLundberg** [comment]
Typically, you don't have to worry about your local copy not matching your github copy.

Soliton has forcibly overwritten your github copy. So the hash keys on your computer no longer match those on github. Until you update your local copy you run the risk of mixing your older hashes (changes) with the newer and that makes a mess of things.

The only change I'd make to his suggestions about when to amend and when to push another commit is my personal rule-of-thumb is one idea, on commit. I will amend for corrections, and make a new commit for a new  subject.

**Comment by soliton-** [comment]
@kallaballa Thanks for your work on this!

There are still some enhancement that would be nice to have in my opinion.
I'll open feature request for those. In case you're interested... ;-)

**Comment by kallaballa** [comment]
what kind of enhancements?

**Comment by soliton-** [comment]
Right, didn't get to opening those issues yet...

I think it'd be nice to either allow the one surrendering to denote which side he surrenders to (and also record that in the replay). And/or to give the one receiving the side the same dialog the host gets when a player leaves the game.
