### ISSUE TITLE
wesnoth-1.16.6 does not compile with boost-1.81:   /usr/include/boost/spirit/include/phoenix_core.hpp:12:1: note: ‘#pragma message: This header is deprecated. Use <boost/phoenix/core.hpp> instead.’

### ISSUE THREAD

**Issue by kobboi** [wesnoth/wesnoth#7215]
### Game and System Information

Version 1.16.6, built from source on up-to-date Gentoo ~amd64

### Description of the bug

The build fails to compile with the latest boost release (1.81)

  /usr/include/boost/spirit/include/phoenix_core.hpp:12:1: note: ‘#pragma message: This header is deprecated. Use <boost/phoenix/core.hpp> instead.’
       12 | BOOST_HEADER_DEPRECATED("<boost/phoenix/core.hpp>")
          | ^~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/boost/spirit/include/phoenix_operator.hpp:12:1: note: ‘#pragma message: This header is deprecated. Use <boost/phoenix/operator.hpp> instead.’
       12 | BOOST_HEADER_DEPRECATED("<boost/phoenix/operator.hpp>")
          | ^~~~~~~~~~~~~~~~~~~~~~~
    /var/tmp/portage/games-strategy/wesnoth-1.16.6/work/wesnoth-1.16.6/src/gettext.cpp: In constructor ‘{anonymous}::translation_manager::translation_manager()’:
    /var/tmp/portage/games-strategy/wesnoth-1.16.6/work/wesnoth-1.16.6/src/gettext.cpp:227:51: error: ‘message_facet’ is not a member of ‘bl’; did you mean ‘message_format’?
      227 |                         generator_.categories(bl::message_facet | bl::information_facet | bl::collation_facet | bl::formatting_facet | bl::convert_facet);
          |                                                   ^~~~~~~~~~~~~
          |

### Additional context

Downstream bug @ https://bugs.gentoo.org/886575 which includes a full build log.

**Comment by Pentarctagon** [comment]
It sounds like the issue fixed by d71e90ee50a89673cf9b6748bcb2975071d15445 ?

**Comment by kobboi** [comment]
Hmm, indeed. Will have to wait for a new 1.16.x release though.

**Comment by Pentarctagon** [comment]
1.16.7 is scheduled to be tagged on Jan 15.

**Comment by kobboi** [comment]
Ok, I will backport the fix for now. Thanks for the quick feedback!

**Comment by Wedge009** [comment]
For the record, the deprecated headers messages are separate to the compilation issue.
