### ISSUE TITLE
Build broken with gcc-4.9.4 on OpenBSD

### ISSUE THREAD

**Issue by yason** [wesnoth/wesnoth#3295]
Hi!
1.14.3 compiles fine with clang-6.0.0 on OpenBSD but fails when compiling witj gcc-4.9.4:
FAILED: src/CMakeFiles/wesnoth-client.dir/gui/dialogs/loading_screen.cpp.o 
/tmp/pobj/wesnoth-1.14.3/bin/c++  -DFIFODIR=\"/var/wesnothd\" -DHAS_RELATIVE_LOCALEDIR=1 -DHAVE_CONFIG_H -DHAVE_FRIBIDI -DHAVE_LIBDBUS -DLOCALEDIR=\"translations\" -DLUA_USE_POSIX -DWESNOTH_PATH=\"/usr/local/share/wesnoth\" -D_X11 -isystem /usr/X11R6/include -isystem /usr/X11R6/include/freetype2 -isystem /usr/local/include/pango-1.0 -isystem /usr/local/include/harfbuzz -isystem /usr/local/include -isystem /usr/local/include/fribidi -isystem /usr/local/include/cairo -isystem /usr/local/include/glib-2.0 -isystem /usr/local/lib/glib-2.0/include -isystem /usr/X11R6/include/pixman-1 -isystem /usr/local/include/libpng16 -isystem /usr/local/include/dbus-1.0 -isystem /usr/local/lib/dbus-1.0/include -isystem /usr/local/include/SDL2 -I/tmp/pobj/wesnoth-1.14.3/wesnoth-1.14.3/src -Isrc -std=c++11 -Wall -Wextra -Werror=non-virtual-dtor -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wold-style-cast -O2 -pipe     -I/usr/local/include -I/usr/local/include/SDL2 -I/usr/X11R6/include -D_REENTRANT -I/usr/X11R6/include -MD -MT src/CMakeFiles/wesnoth-client.dir/gui/dialogs/loading_screen.cpp.o -MF src/CMakeFiles/wesnoth-client.dir/gui/dialogs/loading_screen.cpp.o.d -o src/CMakeFiles/wesnoth-client.dir/gui/dialogs/loading_screen.cpp.o -c /tmp/pobj/wesnoth-1.14.3/wesnoth-1.14.3/src/gui/dialogs/loading_screen.cpp
/tmp/pobj/wesnoth-1.14.3/wesnoth-1.14.3/src/gui/dialogs/loading_screen.cpp: In destructor 'virtual gui2::dialogs::loading_screen::~loading_screen()':
/tmp/pobj/wesnoth-1.14.3/wesnoth-1.14.3/src/gui/dialogs/loading_screen.cpp:208:3: error: 'quick_exit' is not a member of 'std'
   std::quick_exit(0);
   ^

It compiles with gcc-4.9.4 when #else std::quick_exit(0) is removed.
Probably another define needed to use std::_Exit(0) instead of std::quick_exit(0) with gcc4.

**Comment by gfgtdf** [comment]
also note that master will no longer support gcc 4.x so this bug applies only to the 1.14 branch

**Comment by Pentarctagon** [comment]
@jyrkive That's the travis version of GCC, not the docker version.  Docker's GCC version for 1.14 is 5.4:
https://travis-ci.org/wesnoth/wesnoth/jobs/398762728#L495

**Comment by yason** [comment]
What additional info could help?

**Comment by jyrkive** [comment]
@yason This bug report doesn't need any more info. The label was incorrect.

**Comment by Pentarctagon** [comment]
Closing as 1.14 isn't intended to get any further releases at this point.
