### ISSUE TITLE
Broken build after commit faeef96 chrono literals  are not available in C++11

### ISSUE THREAD

**Issue by ilyapopov** [wesnoth/wesnoth#4200]
After commit faeef96, build produces the following error message:

```
../src/gui/dialogs/network_transmission.cpp:36:22: error: ‘chrono_literals’ is not a namespace-name
 using namespace std::chrono_literals;
                      ^~~~~~~~~~~~~~~
../src/gui/dialogs/network_transmission.cpp:36:37: error: expected namespace-name before ‘;’ token
 using namespace std::chrono_literals;
                                     ^
../src/gui/dialogs/network_transmission.cpp: In lambda function:
../src/gui/dialogs/network_transmission.cpp:63:32: error: unable to find numeric literal operator ‘operator""ms’
    std::this_thread::sleep_for(10ms);
                                ^~~~
../src/gui/dialogs/network_transmission.cpp:63:32: note: use -fext-numeric-literals to enable more built-in suffixes
../src/gui/dialogs/network_transmission.cpp: In member function ‘virtual void gui2::dialogs::network_transmission::pump_monitor::process(events::pump_info&)’:
../src/gui/dialogs/network_transmission.cpp:76:22: error: unable to find numeric literal operator ‘operator""ms’
  if(poller_.wait_for(0ms) == std::future_status::ready && poller_.get()) {
                      ^~~
../src/gui/dialogs/network_transmission.cpp:76:22: note: use -fext-numeric-literals to enable more built-in suffixes
```

The problem here is that the code is compiled in C++11 mode, but chrono literals require C++14. See https://en.cppreference.com/w/cpp/chrono/operator%22%22ms

**Comment by ilyapopov** [comment]
PS: I am on branch 1.14 and that commit is on branch 1.14 too. Maybe it is cherry-picked from master by mistake?

**Comment by Vultraz** [comment]
Fixed in 0bd6f91.
