### ISSUE TITLE
Fails to build with boost 1.86.0

### ISSUE THREAD

**Issue by heirecka** [wesnoth/wesnoth#9284]
### Game and System Information

- **Version:** 1.18.2
- **OS:** Linux

### Description of the bug

I noticed wesnoth 1.18.2 fails to build with boost 1.86.0. Same with current master, too:
```

/var/tmp/paludis/build/games-strategy-wesnoth-1.18.2/work/wesnoth-1.18.2/src/server/common/server_base.cpp: In member function 'void server_base::start_server()':
/var/tmp/paludis/build/games-strategy-wesnoth-1.18.2/work/wesnoth-1.18.2/src/server/common/server_base.cpp:84:27: error: call of overloaded 'spawn(boost::asio::io_service&, server_base::start_server()::<lambda(boost::asio::yield_context)>)' is ambiguous
   84 |         boost::asio::spawn(io_service_, [this, endpoint_v6](boost::asio::yield_context yield) { serve(yield, acceptor_v6_, endpoint_v6); });
      |         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/x86_64-pc-linux-gnu/include/boost/asio/spawn.hpp:871,
                 from /var/tmp/paludis/build/games-strategy-wesnoth-1.18.2/work/wesnoth-1.18.2/src/server/common/server_base.hpp:41,
                 from /var/tmp/paludis/build/games-strategy-wesnoth-1.18.2/work/wesnoth-1.18.2/src/server/common/server_base.cpp:16:
/usr/x86_64-pc-linux-gnu/include/boost/asio/impl/spawn.hpp:1134:13: note: candidate: 'decltype (async_initiate<CompletionToken, typename boost::asio::detail::spawn_signature<typename boost::asio::result_of<F(boost::asio::basic_yield_context<typename ExecutionContext::executor_type>)>::type>::type>(declval<boost::asio::detail::initiate_spawn<typename ExecutionContext::executor_type> >(), token, static_cast<F&&>(function))) boost::asio::spawn(ExecutionContext&, F&&, CompletionToken&&, constraint_t<((bool)(! std::is_same<typename std::decay<Property>::type, boost::coroutines::attributes>::value))>, constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)>) [with ExecutionContext = io_context; F = server_base::start_server()::<lambda(yield_context)>; CompletionToken = deferred_t; decltype (async_initiate<CompletionToken, typename detail::spawn_signature<typename result_of<F(basic_yield_context<typename ExecutionContext::executor_type>)>::type>::type>(declval<detail::initiate_spawn<typename ExecutionContext::executor_type> >(), token, static_cast<F&&>(function))) = deferred_async_operation<void(std::__exception_ptr::exception_ptr), detail::initiate_spawn<io_context::basic_executor_type<std::allocator<void>, 0> >, server_base::start_server()::<lambda(yield_context)> >; typename detail::spawn_signature<typename result_of<F(basic_yield_context<typename ExecutionContext::executor_type>)>::type>::type = void(std::__exception_ptr::exception_ptr); typename result_of<F(basic_yield_context<typename ExecutionContext::executor_type>)>::type = void; typename ExecutionContext::executor_type = io_context::basic_executor_type<std::allocator<void>, 0>; constraint_t<((bool)(! std::is_same<typename std::decay<Property>::type, boost::coroutines::attributes>::value))> = int; typename std::decay<Property>::type = deferred_t; constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)> = int]'
 1134 | inline auto spawn(ExecutionContext& ctx, F&& function, CompletionToken&& token,
      |             ^~~~~
/usr/x86_64-pc-linux-gnu/include/boost/asio/impl/spawn.hpp:1385:13: note: candidate: 'void boost::asio::spawn(ExecutionContext&, Function&&, const boost::coroutines::attributes&, constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)>) [with Function = server_base::start_server()::<lambda(yield_context)>; ExecutionContext = io_context; constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)> = int]'
 1385 | inline void spawn(ExecutionContext& ctx, Function&& function,
      |             ^~~~~
/var/tmp/paludis/build/games-strategy-wesnoth-1.18.2/work/wesnoth-1.18.2/src/server/common/server_base.cpp:87:27: error: call of overloaded 'spawn(boost::asio::io_service&, server_base::start_server()::<lambda(boost::asio::yield_context)>)' is ambiguous
   87 |         boost::asio::spawn(io_service_, [this, endpoint_v4](boost::asio::yield_context yield) { serve(yield, acceptor_v4_, endpoint_v4); });
      |         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/x86_64-pc-linux-gnu/include/boost/asio/impl/spawn.hpp:1134:13: note: candidate: 'decltype (async_initiate<CompletionToken, typename boost::asio::detail::spawn_signature<typename boost::asio::result_of<F(boost::asio::basic_yield_context<typename ExecutionContext::executor_type>)>::type>::type>(declval<boost::asio::detail::initiate_spawn<typename ExecutionContext::executor_type> >(), token, static_cast<F&&>(function))) boost::asio::spawn(ExecutionContext&, F&&, CompletionToken&&, constraint_t<((bool)(! std::is_same<typename std::decay<Property>::type, boost::coroutines::attributes>::value))>, constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)>) [with ExecutionContext = io_context; F = server_base::start_server()::<lambda(yield_context)>; CompletionToken = deferred_t; decltype (async_initiate<CompletionToken, typename detail::spawn_signature<typename result_of<F(basic_yield_context<typename ExecutionContext::executor_type>)>::type>::type>(declval<detail::initiate_spawn<typename ExecutionContext::executor_type> >(), token, static_cast<F&&>(function))) = deferred_async_operation<void(std::__exception_ptr::exception_ptr), detail::initiate_spawn<io_context::basic_executor_type<std::allocator<void>, 0> >, server_base::start_server()::<lambda(yield_context)> >; typename detail::spawn_signature<typename result_of<F(basic_yield_context<typename ExecutionContext::executor_type>)>::type>::type = void(std::__exception_ptr::exception_ptr); typename result_of<F(basic_yield_context<typename ExecutionContext::executor_type>)>::type = void; typename ExecutionContext::executor_type = io_context::basic_executor_type<std::allocator<void>, 0>; constraint_t<((bool)(! std::is_same<typename std::decay<Property>::type, boost::coroutines::attributes>::value))> = int; typename std::decay<Property>::type = deferred_t; constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)> = int]'
 1134 | inline auto spawn(ExecutionContext& ctx, F&& function, CompletionToken&& token,
      |             ^~~~~
/usr/x86_64-pc-linux-gnu/include/boost/asio/impl/spawn.hpp:1385:13: note: candidate: 'void boost::asio::spawn(ExecutionContext&, Function&&, const boost::coroutines::attributes&, constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)>) [with Function = server_base::start_server()::<lambda(yield_context)>; ExecutionContext = io_context; constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)> = int]'
 1385 | inline void spawn(ExecutionContext& ctx, Function&& function,
      |             ^~~~~
/var/tmp/paludis/build/games-strategy-wesnoth-1.18.2/work/wesnoth-1.18.2/src/server/common/server_base.cpp: In member function 'void server_base::serve(boost::asio::yield_context, boost::asio::ip::tcp::acceptor&, boost::asio::ip::tcp::endpoint)':
/var/tmp/paludis/build/games-strategy-wesnoth-1.18.2/work/wesnoth-1.18.2/src/server/common/server_base.cpp:125:35: error: call of overloaded 'spawn(boost::asio::io_service&, server_base::serve(boost::asio::yield_context, boost::asio::ip::tcp::acceptor&, boost::asio::ip::tcp::endpoint)::<lambda(boost::asio::yield_context)>)' is ambiguous
  125 |                 boost::asio::spawn(io_service_, [this, &acceptor, endpoint](boost::asio::yield_context yield) { serve(yield, acceptor, endpoint); });
      |                 ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/x86_64-pc-linux-gnu/include/boost/asio/impl/spawn.hpp:1134:13: note: candidate: 'decltype (async_initiate<CompletionToken, typename boost::asio::detail::spawn_signature<typename boost::asio::result_of<F(boost::asio::basic_yield_context<typename ExecutionContext::executor_type>)>::type>::type>(declval<boost::asio::detail::initiate_spawn<typename ExecutionContext::executor_type> >(), token, static_cast<F&&>(function))) boost::asio::spawn(ExecutionContext&, F&&, CompletionToken&&, constraint_t<((bool)(! std::is_same<typename std::decay<Property>::type, boost::coroutines::attributes>::value))>, constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)>) [with ExecutionContext = io_context; F = server_base::serve(boost::asio::yield_context, boost::asio::ip::tcp::acceptor&, boost::asio::ip::tcp::endpoint)::<lambda(yield_context)>; CompletionToken = deferred_t; decltype (async_initiate<CompletionToken, typename detail::spawn_signature<typename result_of<F(basic_yield_context<typename ExecutionContext::executor_type>)>::type>::type>(declval<detail::initiate_spawn<typename ExecutionContext::executor_type> >(), token, static_cast<F&&>(function))) = deferred_async_operation<void(std::__exception_ptr::exception_ptr), detail::initiate_spawn<io_context::basic_executor_type<std::allocator<void>, 0> >, server_base::serve(boost::asio::yield_context, boost::asio::ip::tcp::acceptor&, boost::asio::ip::tcp::endpoint)::<lambda(yield_context)> >; typename detail::spawn_signature<typename result_of<F(basic_yield_context<typename ExecutionContext::executor_type>)>::type>::type = void(std::__exception_ptr::exception_ptr); typename result_of<F(basic_yield_context<typename ExecutionContext::executor_type>)>::type = void; typename ExecutionContext::executor_type = io_context::basic_executor_type<std::allocator<void>, 0>; constraint_t<((bool)(! std::is_same<typename std::decay<Property>::type, boost::coroutines::attributes>::value))> = int; typename std::decay<Property>::type = deferred_t; constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)> = int]'
 1134 | inline auto spawn(ExecutionContext& ctx, F&& function, CompletionToken&& token,
      |             ^~~~~
/usr/x86_64-pc-linux-gnu/include/boost/asio/impl/spawn.hpp:1385:13: note: candidate: 'void boost::asio::spawn(ExecutionContext&, Function&&, const boost::coroutines::attributes&, constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)>) [with Function = server_base::serve(boost::asio::yield_context, boost::asio::ip::tcp::acceptor&, boost::asio::ip::tcp::endpoint)::<lambda(yield_context)>; ExecutionContext = io_context; constraint_t<((bool)std::is_convertible<ExecutionContext&, execution_context&>::value)> = int]'
 1385 | inline void spawn(ExecutionContext& ctx, Function&& function,
      |
```

**Comment by Wedge009** [comment]
My Linux system has boost 1.83 and compiles successfully. It looks like there was an update to [spawn](https://www.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/spawn.html) in [boost 1.84](https://www.boost.org/users/history/version_1_84_0.html), however the `vcpkg` configuration in Wesnoth master currently uses boost 1.84 and there doesn't appear to be any problem compiling in MSVC.

Presumably your build was working previously - which boost were you using then?

**Comment by heirecka** [comment]
> Presumably your build was working previously - which boost were you using then?

Yes, with the previous, 1.85.0, the build was working fine

**Comment by gfgtdf** [comment]
maybe we should just report this upstream then

**Comment by soliton-** [comment]
Does the following diff fix the build for you?

```diff
diff --git a/src/server/common/server_base.cpp b/src/server/common/server_base.cpp
index 51f77969683..943d46799ce 100644
--- a/src/server/common/server_base.cpp
+++ b/src/server/common/server_base.cpp
@@ -81,10 +81,10 @@ server_base::server_base(unsigned short port, bool keep_alive)
 void server_base::start_server()
 {
        boost::asio::ip::tcp::endpoint endpoint_v6(boost::asio::ip::tcp::v6(), port_);
-       boost::asio::spawn(io_service_, [this, endpoint_v6](boost::asio::yield_context yield) { serve(yield, acceptor_v6_, endpoint_v6); });
+       boost::asio::spawn(io_service_, [this, endpoint_v6](boost::asio::yield_context yield) { serve(yield, acceptor_v6_, endpoint_v6); }, [](std::exception_ptr e) { if (e) std::rethrow_exception(e); });

        boost::asio::ip::tcp::endpoint endpoint_v4(boost::asio::ip::tcp::v4(), port_);
-       boost::asio::spawn(io_service_, [this, endpoint_v4](boost::asio::yield_context yield) { serve(yield, acceptor_v4_, endpoint_v4); });
+       boost::asio::spawn(io_service_, [this, endpoint_v4](boost::asio::yield_context yield) { serve(yield, acceptor_v4_, endpoint_v4); }, [](std::exception_ptr e) { if (e) std::rethrow_exception(e); });

        handshake_response_ = htonl(42);

@@ -122,7 +122,7 @@ void server_base::serve(boost::asio::yield_context yield, boost::asio::ip::tcp::
        }

        if(accepting_connections()) {
-               boost::asio::spawn(io_service_, [this, &acceptor, endpoint](boost::asio::yield_context yield) { serve(yield, acceptor, endpoint); });
+               boost::asio::spawn(io_service_, [this, &acceptor, endpoint](boost::asio::yield_context yield) { serve(yield, acceptor, endpoint); }, [](std::exception_ptr e) { if (e) std::rethrow_exception(e); });
        } else {
                return;
        }
```

**Comment by Wedge009** [comment]
I tried to set-up boost 1.86 from source but I build Wesnoth on Linux with SCons and I don't know how to get it to find the downloaded boost rather than the system boost packages. The `SConstruct` file seems to make use of `CheckBoost` functionality but I don't see the implementation details for that.

**Comment by Wedge009** [comment]
Never mind, I realised the initial installation attempt didn't actually work. I can confirm this issue now, looking at soliton's suggestion...

**Comment by Wedge009** [comment]
I see no difference in the [boost documentation](https://www.boost.org/doc/libs/1_86_0/doc/html/boost_asio/reference/spawn.html) for `spawn` between 1.85 and 1.86, but making the following change allowed the build to complete for me:

```
diff --git a/src/server/common/server_base.cpp b/src/server/common/server_base.cpp
index 1ed63200d7a..76f54859f51 100644
--- a/src/server/common/server_base.cpp
+++ b/src/server/common/server_base.cpp
@@ -74,10 +74,10 @@ server_base::server_base(unsigned short port, bool keep_alive)
 void server_base::start_server()
 {
        boost::asio::ip::tcp::endpoint endpoint_v6(boost::asio::ip::tcp::v6(), port_);
-       boost::asio::spawn(io_service_, [this, endpoint_v6](boost::asio::yield_context yield) { serve(yield, acceptor_v6_, endpoint_v6); });
+       boost::asio::spawn(io_service_, [this, endpoint_v6](boost::asio::yield_context yield) { serve(yield, acceptor_v6_, endpoint_v6); }, [](std::exception_ptr e) { if (e) std::rethrow_exception(e); });
 
        boost::asio::ip::tcp::endpoint endpoint_v4(boost::asio::ip::tcp::v4(), port_);
-       boost::asio::spawn(io_service_, [this, endpoint_v4](boost::asio::yield_context yield) { serve(yield, acceptor_v4_, endpoint_v4); });
+       boost::asio::spawn(io_service_, [this, endpoint_v4](boost::asio::yield_context yield) { serve(yield, acceptor_v4_, endpoint_v4); }, [](std::exception_ptr e) { if (e) std::rethrow_exception(e); });
 
        handshake_response_ = htonl(42);
 
@@ -115,7 +115,7 @@ void server_base::serve(boost::asio::yield_context yield, boost::asio::ip::tcp::
        }
 
        if(accepting_connections()) {
-               boost::asio::spawn(io_service_, [this, &acceptor, endpoint](boost::asio::yield_context yield) { serve(yield, acceptor, endpoint); });
+               boost::asio::spawn(io_service_, [this, &acceptor, endpoint](boost::asio::yield_context yield) { serve(yield, acceptor, endpoint); }, [](std::exception_ptr e) { if (e) std::rethrow_exception(e); });
        } else {
                return;
        }
@@ -559,7 +559,8 @@ template<class SocketPtr> void server_base::async_send_doc_queued(SocketPtr sock
        boost::asio::spawn(
                io_service_, [this, doc_ptr = doc.clone(), socket](boost::asio::yield_context yield) mutable {
                        send_doc_queued(socket, doc_ptr, yield);
-               }
+               },
+               [](std::exception_ptr e) { if (e) std::rethrow_exception(e); }
        );
 }
 
diff --git a/src/server/wesnothd/server.cpp b/src/server/wesnothd/server.cpp
index f068e655169..bb5bf98af9e 100644
--- a/src/server/wesnothd/server.cpp
+++ b/src/server/wesnothd/server.cpp
@@ -666,12 +666,12 @@ void server::refresh_tournaments(const boost::system::error_code& ec)
 
 void server::handle_new_client(socket_ptr socket)
 {
-       boost::asio::spawn(io_service_, [socket, this](boost::asio::yield_context yield) { login_client(yield, socket); });
+       boost::asio::spawn(io_service_, [socket, this](boost::asio::yield_context yield) { login_client(yield, socket); }, [](std::exception_ptr e) { if (e) std::rethrow_exception(e); });
 }
 
 void server::handle_new_client(tls_socket_ptr socket)
 {
-       boost::asio::spawn(io_service_, [socket, this](boost::asio::yield_context yield) { login_client(yield, socket); });
+       boost::asio::spawn(io_service_, [socket, this](boost::asio::yield_context yield) { login_client(yield, socket); }, [](std::exception_ptr e) { if (e) std::rethrow_exception(e); });
 }
 
 template<class SocketPtr>
@@ -776,7 +776,8 @@ void server::login_client(boost::asio::yield_context yield, SocketPtr socket)
        coro_send_doc(socket, join_lobby_response, yield);
 
        boost::asio::spawn(io_service_,
-               [this, socket, new_player](boost::asio::yield_context yield) { handle_player(yield, socket, new_player); }
+               [this, socket, new_player](boost::asio::yield_context yield) { handle_player(yield, socket, new_player); },
+               [](std::exception_ptr e) { if (e) std::rethrow_exception(e); }
        );
 
        LOG_SERVER << log_address(socket) << "\t" << username << "\thas logged on"
```

I don't really understand the `spawn` function, though, so I can't see if this is something that needs to be done in Wesnoth or if, as gfgtdf implied, this is an unintentional change in boost 1.86.

**Comment by Wedge009** [comment]
In boost 1.80, `spawn` was '[changed to be a completion token-based asynchronous operation](https://www.boost.org/users/history/version_1_80_0.html)', but the completion token was given a [default](https://www.boost.org/doc/libs/1_80_0/doc/html/boost_asio/reference/spawn.html).

For some reason, it looks like the compiler can't find the right overload any more, where no completion token is specified. So is this an issue with the compiler or with boost?

**Comment by Wedge009** [comment]
Reported in https://github.com/chriskohlhoff/asio/issues/1524, just in case ([boostorg](https://github.com/boostorg/asio/issues/new/choose) advises to submit new issues there).

**Comment by soliton-** [comment]
> I don't really understand the `spawn` function, though, so I can't see if this is something that needs to be done in Wesnoth or if, as gfgtdf implied, this is an unintentional break in boost 1.86.

Since it doesn't work with released boost versions we should add a workaround either way but I do think this is not intentional from the boost side so thanks for reporting it there. And thanks for the complete diff.

**Comment by Wedge009** [comment]
@heirecka Are you sure your build with boost 1.85 doesn't have issues with `asio::spawn`? I just tried compiling cleanly and am still getting build errors with this function.

**Comment by soliton-** [comment]
If you installed to a non-default path then perhaps you need to set `LD_LIBRARY_PATH` or maybe you need to run `ldconfig`.

**Comment by Wedge009** [comment]
I just reverted to the system-packaged boost.

**Comment by Wedge009** [comment]
@soliton- Where in the docs does it say the behaviour (of relying on a default) is deprecated? I note you specify the tokens for boost version 1.80 and later. Anyway, thanks for fixing that.

**Comment by soliton-** [comment]
> @soliton- Where in the docs does it say the behaviour (of relying on a default) is deprecated?

I don’t think it says that anywhere. `spawn` overloads without completion token are deprecated.

**Comment by Wedge009** [comment]
That's what I'm trying to understand. If it's not stated in the documentation, where do you determine that the form Wesnoth was using is deprecated?

**Comment by soliton-** [comment]
To be clear I've nothing against the upstream issue you reported. I agree with it. Nevertheless we want wesnoth building with boost 1.86 and we want to stop using deprecated functionality. While switching to the token completion overloads we need to specify the throwing behavior to keep it working as before.

**Comment by Wedge009** [comment]
I appreciate that, I was just trying to understand how you came to the conclusion that the function without the completion token is deprecated... but reviewing the documentation I cited earlier it does indeed state that the form without the completion token explicitly given is indeed deprecated.
