### ISSUE TITLE
Some tools are still Python 2 (GNA #23897)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1508]
**[Original submission](https://gna.org/bugs/index.php?23897)** by limburgher on 2015-09-22

This issue was originally about a build error but it changed topic and is now about python2 scripts and python2 being EOL

<details>

<summary>new topic: python2 is EOL</summary>

We still have python2 scripts around even though python2 is EOL. They should be upgraded to python3 or removed.

- [x] data/tools/wesnoth/wmlparser.py - pure python parser, does not need a wesnoth executable (like wmlparser2/3)
- [ ] data/tools/wesnoth/wmlparser2.py - obsoleted by wmlparser3 if no python2 code is left that uses it
- [x] data/tools/wesnoth/wmldata.py
- [x] data/tools/wesnoth/wmgrammar.py
- [x] data/tools/rmtrans/rmtrans.py
- [x] data/tools/scoutDefault.py
- [x] data/tools/unit_tree/overview.py
- [x] data/tools/expand-terrain-macros.py
- [x] utils/unused_functions.py
- [x] utils/wiki_grabber.py
- [x] utils/ai_test/ai_test.py

- [x] utils/wescamp_import
- [x] utils/umc_dev/build/update_version
- [x] utils/codelist
- [x] data/tools/wmlvalidator
- [x] data/tools/wmlflip
- [x] data/tools/trackplacer
- [x] data/tools/journeylifter

</details>

<details>

<summary>original topic: build error on fedora</summary>

Build log for 1.12.4 against Fedora rawhide ends with:

g++ -o build/release/tests/main.o -c -std#c++98 -W -O2 -O2 -g -pipe -Wall -Werrorformat-security -fexceptions -fstack-protector-strong --param#ssp-buffer-size4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 

src/tests/main.cpp:98:3: error: expected initializer at end of input

 BOOST_GLOBAL_FIXTURE(wesnoth_global_fixture)

   ^

scons: *** [build/release/tests/main.o] Error 1

scons: building terminated because of errors.

I also tried the most recent git version but it fails for another reason:

Bytecompiling .py files below /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.1-0.fc24git52558d.x86_64/usr/lib/python2.7 using /usr/bin/python2.7

Compiling /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.1-0.fc24git52558d.x86_64/usr/share/wesnoth/data/tools/wesnoth/wmlparser3.py ...

  File "/usr/share/wesnoth/data/tools/wesnoth/wmlparser3.py", line 81

    def __init__(self, data : bytes):

                            ^

SyntaxError: invalid syntax

(Reproduced on Linux)
Release: 1.13.x
Priority: 5 - Normal
Severity: 4 - Important

</details>

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-22**

**anonymous wrote:**

> first issue: 
> 
> seems like a semicolon missing after BOOST_GLOBAL_FIXTURE
> 
> second issue:
> 
> afaik wmlparser3 i meant to be used with python3.
> 
> 
> 
> both the boost tests and the python tools are not necessary to play wesnoth, you should try to disable these things from your build.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-23**

**limburgher wrote:**

> That worked, thanks!  Hopefully the tests will be updated sometime in the 1.13.x cycle.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-19**

**shadowmaster changed title:** Neither 1.12.x nor 1.13.x builds with boost 1.59.0 -> Neither 1.12.x nor 1.13.x unit tests build with boost 1.59.0

**shadowmaster changed item group:** None of the others -> Unit Tests

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-12-30**

**aginor changed status:** None -> Ready For Test

**aginor wrote:**

> This may be fixed by https://gna.org/bugs/?24234
> 
> 
> 
> Could you please re-test?

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-01-05**

**limburgher wrote:**

> No, it fails with, for git snapshot starting with f997b4:
> 
> 
> 
> src/tests/utils/auto_parameterized.hpp:75:73: error: no matching function for call to 'make_test_case(void (*)(const test_network::sendfile_param&), boost::unit_test::const_string, test_network::sendfile_param*&, test_network::sendfile_param*&)'
> 
>                BOOST_JOIN(test_name, _begin), BOOST_JOIN(test_name, _end))); \
> 
>                                                                          ^
> 
> src/tests/test_network_worker.cpp:262:1: note: in expansion of macro 'WESNOTH_PARAMETERIZED_TEST_CASE'
> 
>  WESNOTH_PARAMETERIZED_TEST_CASE( test_multi_sendfile, sendfile_param, sendfile_sizes, size )
> 
>  ^
> 
> etc. . . .
> 
> 
> 
> If I disable tests I get a Python error towards the end of the RPM build process:
> 
> 
> 
> Bytecompiling .py files below /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.2-0.git594ce7.fc24.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
> 
> Compiling /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.2-0.git594ce7.fc24.x86_64/usr/lib/python2.7/site-packages/wesnoth/campaignserver_client.py ...
> 
>   File "/usr/lib/python2.7/site-packages/wesnoth/campaignserver_client.py", line 18
> 
>     def append_tag(tag : wmlparser.TagNode, sub : str) -> wmlparser.TagNode:
> 
>                        ^
> 
> SyntaxError: invalid syntax

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-01-16**

**aginor changed status:** Ready For Test -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-08**

**limburgher wrote:**

> I'm still getting the Python error on 1.13.5, can you have a look?  I'd like to update rawhide to 1.13.5 if possible.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-09**

**aginor changed status:** Confirmed -> In Progress

**aginor wrote:**

> I'll have a look.
> 
> From the looks of things I'll have to figure out how to build RPMs, which it's been 10+ years since I did the last time so it might take me a little while.
> 
> 
> 
> Have you done any other modifications than to take the spec-file from a previous release and updated?
> 
> 
> 
> Is boost 1.59 still a priority?

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-09**

**limburgher wrote:**

> Boost is fine, it's just the Python syntax error:
> 
> 
> 
> Bytecompiling .py files below /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.2-0.git594ce7.fc24.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
> 
> Compiling /home/limb/rpmbuild/BUILDROOT/wesnoth-1.13.2-0.git594ce7.fc24.x86_64/usr/lib/python2.7/site-packages/wesnoth/campaignserver_client.py ...
> 
> File "/usr/lib/python2.7/site-packages/wesnoth/campaignserver_client.py", line 18
> 
> def append_tag(tag : wmlparser.TagNode, sub : str) -> wmlparser.TagNode:
> 
> ^
> 
> SyntaxError: invalid syntax

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-10**

**shadowmaster wrote:**

> data/tools/wesnoth/campaignserver_client.py is supposed to be run with Python 3 since version 1.13.2, and the log excerpt you posted makes it seem like something in the pipeline is assuming Python 2.
> 
> 
> 
> Perhaps adding a /usr/bin/python3 shebang to it would solve the issue? Note that normally it wouldn't need one since it's not intended to be run on its own, but rather it's imported by data/tools/wesnoth_addon_manager which does have the correct shebang.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-10**

**limburgher wrote:**

> Right, the RPM byte compiler assumes Python2.  When I change it to Python3 it discovers other scripts whose syntax is invalid for Python3.  Is the project currently a mix of both 2 and 3?

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-29**

**aginor changed status:** In Progress -> None

**Comment by sevu** [comment]
@limburgher
When byte compiling for the RPM package, would it be possible to specify the 
commands for each file or folder separately? 

Currently the tools are a mix of python 2 and 3.
We could probably make a list which file needs what python version in the packaging script.

**Comment by limburgher** [comment]
I was able to work around it by allowing for both 2 and 3.  It would be nice to move completely to 3, but we're fine for now.

**Comment by CelticMinstrel** [comment]
Which tools are still using Python 2? I thought @Elvish-Hunter had worked really hard to convert all of them.

**Comment by Elvish-Hunter** [comment]
Yes, I didn't manage to convert all the tools to Python 3 yet due to time constraints.
Also, @limburgher's find command doesn't catch those tools that don't have a .py extension, like trackplacer (which can't just be ported, but requires to be rewritten from scratch) or wmllint (which is already converted instead).

**Comment by limburgher** [comment]
Any updates on this? Python 2 is EOL in January 2020.

**Comment by soliton-** [comment]
Several of those have python3 versions. I wouldn't hold my breath that every python2 script will be removed anytime soon. Those are not essential scripts.

Of course anyone is welcome to port the remaining ones...

**Comment by limburgher** [comment]
Ok, thanks. I'm excluding the python 2 scripts for now. I may do some porting if I have a moment.

**Comment by jostephd** [comment]
Added to the OP a list of affected scripts. Please tick anything that's been converted or that doesn't need to be converted. Is there anything in there that should be prioritized?

**Comment by Elvish-Hunter** [comment]
In 9982afb, I converted `expand-terrain-macros` to Python 3, and I also marked it in the OP.
As for `rmtrans.py`, I marked it because it's a Gimp plugin: as such, it cannot be converted until that program starts supporting Python 3. An alternative approach might be converting it as a pure Python script, to be called from the command line.

**Comment by Vultraz** [comment]
How many of those are even actually used anymore? I'm pretty sure most of the ones we actually use often have been ported, and I wouldn't want you putting time into code no one uses anymore.

**Comment by Elvish-Hunter** [comment]
> How many of those are even actually used anymore?

@Vultraz I'm not really sure about that; however, I found a potential candidate for deletion. It's the `tools/scoutDefault.py` script, which appeared in [this forum topic](https://forums.wesnoth.org/viewtopic.php?f=10&t=14739) from 2007 (!). I don't even know if anyone has ever used it since then...
Should I update it, or should we drop it?

**Comment by Vultraz** [comment]
Drop it and anything else that's unused.

**Comment by soliton-** [comment]
`data/tools/scoutDefault.py` can definitely be removed. I'm not sure it was ever used again either.
`utils/wescamp_import` is probably not useful anymore since wescamp is abandoned.
Not sure why `data/tools/unit_tree/overview.py` is in the list since it has a python3 shebang.

Hard to tell if no one uses the others.

**Comment by jostephd** [comment]
>  Not sure why `data/tools/unit_tree/overview.py` is in the list since it has a python3 shebang.

Not sure either, and I didn't keep the commands I used to generate the list, so it's anyone's guess.

**Comment by jostephd** [comment]
> Not sure either, and I didn't keep the commands I used to generate the list, so it's anyone's guess.

Figured it out. The list in the OP is a combination of two lists, https://github.com/wesnoth/wesnoth/issues/1508#issuecomment-327179532 and my own survey of files that _don't_ have a .py extension. overview.py has a py extension so it'll be from https://github.com/wesnoth/wesnoth/issues/1508#issuecomment-327179532. That comment is from 2017 and at that time that script did have a `python2` shebang.

**Comment by stevecotton** [comment]
`data/tools/journeylifter` is another one to delete - it's a tool from 2008 (pre Wesnoth 1.5.6) to convert pre-trackplacer maps to trackplacer format.

**Comment by Elvish-Hunter** [comment]
Since we agreed on that, I removed `scoutDefault` in 2863db3.

> `data/tools/journeylifter` is another one to delete - it's a tool from 2008 (pre Wesnoth 1.5.6) to convert pre-trackplacer maps to trackplacer format.

It'd be interesting to know how many add-ons from the 1.2 - 1.4 releases used the old DOT/CROSS macros and were never ported to a later version of Wesnoth... Very few, I suspect; however, these are the only UMCs that might benefit from the script.
If nobody has anything against this, I'm going to remove `journeylifter` as well.

**Comment by soliton-** [comment]
1.2
- A_Princes_Tale
- Eternal_Kingdom
- Return_of_the_Legions
- Wesvoid

1.4
- Elvish_Legacy
- Tarlyn

I've already removed the ones I could easily tell were ported. So if any at all that's not a lot.

**Comment by Elvish-Hunter** [comment]
@soliton- I checked the add-ons you listed, and the situation is even worse:

- A_Princes_Tale is not compatible due to having its journey tracks inside of a `bigmap.cfg` file (journeylifter expects them to be inside the scenarios);
- Wesvoid has almost all of its `DOT/CROSS` macros commented out, so wmllint won't convert them anyway;
- Elvish_Legacy doesn't have its scenarios numbered, so the files won't sort correctly and journeylifter expects them to do so;
- Tarlyn isn't compatible since it has two `*story.cfg` files;
- Eternal_Kingdom crashes wmllint due to an empty `#ifdef`, so no conversion can happen;
- Return_of_the_Legion is the only add-on that, at a first check, seems to be accepted by journeylifter.

One single add-on doesn't justify keeping that tool, this is why I removed `journeylifter` in b896517.

**Comment by jostephd** [comment]
> One single add-on doesn't justify keeping that tool, this is why I removed `journeylifter` in [b896517](https://github.com/wesnoth/wesnoth/commit/b8965178348fab03718fb4b7fb798e8427d7cbb9).

For future reference - if anyone ever needs journeyfilter again and tries to resurrect it from old releases - I think it'll work with python3 as soon as `print foo` is changed to `print(foo)` and the shebang line is changed.

**Comment by Elvish-Hunter** [comment]
I ported `wmlflip` to Python 3 in 1fe32ff. However, the work on this script isn't yet finished: it still needs to have `getopt` replaced with `argparse`, have the % string formatting replaced with the `.format()` method and be tested on Windows.

**Comment by Elvish-Hunter** [comment]
I just found that the script in `/utils/po_stat.py` has a `/usr/bin/env python` shebang line, so it isn't clear whether it's Python 2 or 3. When running `2to3` on it, however, round braces are added to `print()` calls, but they already have them. To me, it looks like it's already in Python 3, so I'm just going to update its shebang.
As for `utils/wescamp_import`, as soliton pointed out, Wescamp is dead (its latest real commits happened in 2014, plus two in 2017...); moreover, the script doesn't perform its actions directly, but instead generates a Bash script, which is useless for developers on Windows (unless they install Cygwin or the Windows Subsystem for Linux, but I have no idea whether it'll work correctly in such cases). For these reasons, I believe that the best course of action is to remove wescamp_import. Anyone against this?

**Comment by Elvish-Hunter** [comment]
I updated the shebang line in both `po_stat.py` and `codelist` (I know that @jostephd ported this one to Py3, but we can't take chances with most Linux boxes still aliasing `python` to `python2`) in b4d855c.
`wescamp_import` has been removed in dbe9d60.

**Comment by Elvish-Hunter** [comment]
In these days, I tried working on wmlvalidator and its dependencies. After spending a lot of time on it, I can tell you what I found.
Updating the scripts to Python 3 was fairly simple, except for an ugly UTF-8 workaround that in Python 3 isn't needed any more. However, when I tried running wmlvalidator, all I was able to get was this error:

        for type in schema.get_all_text():
    AttributeError: 'NoneType' object has no attribute 'get_all_text'

Long short story, the script required a schema to run, but expected it to start with a `[schema]` tag, instead of the `[wml_schema]` that we're currently using. Trying to update that point led to another error in `wmlgrammar.py`:

        if parts[1] not in datatypes:
    IndexError: list index out of range

The problem here is that the old `/data/schema.cfg` file had a very different structure than our current schemas: each key had a pair of values separated by a space, stating whether the key was required or optional and the allowed values, and it didn't contain macros.
At this point, I'd say that wmlvalidator is broken beyond repair and its (incomplete) functionality is already performed by the C++ engine with the `--validate` switch, so my proposal is to remove it along with its dependency wmlgrammar, since it doesn't have any purpose other than being used by the main script.
wmldata and wmlparser (the other two dependencies) can be updated to Py3, so later we can see if there's still some chance of salvaging them.
Let me know if I can go ahead.

**Comment by Elvish-Hunter** [comment]
I removed wmlvalidator and wmlgrammar in 5654b4c.
In a830561, I ported wmldata and wmlparser to Python 3; for now, they seem to work, but there's no warranty that they're working *correctly*. For example, it looks like wmlparser isn't correctly substituting macros, and this happened even before porting it to Py3: as I wrote before, we'll see later if they can be fixed or not.

**Comment by Elvish-Hunter** [comment]
`utils/umc_dev/build/update version` and `utils/wiki_grabber.py` have been ported to Python 3 in af64a10 and 4f66725.

**Comment by Elvish-Hunter** [comment]
'utils/ai_test/ai_test.py', its cfg file and 'utils/unused_functions.py' have been ported to Python 3 in ffc5edd and 636f29b.
Now, all that's left is removing wmlparser2 (unless someone is still using it somewhere) and rewriting trackplacer (but this one requires a fair amount of time).

**Comment by stevecotton** [comment]
PR for rewriting trackplacer as a conversion tool to use Tiled's UI #4464

**Comment by stevecotton** [comment]
> Now, all that's left is removing wmlparser2 (unless someone is still using it somewhere)

I think we should remove it and see if anyone wants it back. I've added that in the roadmap for 1.15.4.

The rmtrans.py utility is still Python2, but that's a transient dependency on Gimp2 (and can't be fixed until Gimp3).

**Comment by loonycyborg** [comment]
> there's two new Python2 scripts, utils/dockerbuilds/mingw/get_dlls.py and utils/update_appdata. Does the mingw environment require them to be Python2?
What do you mean? They don't have forced python2 in shebang line and I have python3 as system python so I'm mostly running them with py3. Don't remember what it's using inside docker containers though.

**Comment by stevecotton** [comment]
On the shebang line, "python" normally means python2, although that can be overridden with the PY_PYTHON environment variable: https://docs.python.org/dev/using/windows.html#from-a-script

However, `#!/bin/env python` doesn't have the same effect as `#!/usr/bin/env python`: https://docs.python.org/dev/using/windows.html#shebang-lines

**Comment by loonycyborg** [comment]
Feel free to fix shebang lines if they're wrong. In any case scripts themselves were written on py3 and are supposed to be used with it too.

**Comment by Elvish-Hunter** [comment]
> The rmtrans.py utility is still Python2, but that's a transient dependency on Gimp2 (and can't be fixed until Gimp3).

Indeed it's a Gimp plug-in, however we don't know how many people actually use it (maybe none?). Does anyone think that it might be a good idea replacing it with a command line version based on the Pillow library?

**Comment by stevecotton** [comment]
@loonycyborg thanks, will do that in my next PR

@Elvish-Hunter thanks, the more I look at it, the more I think "maybe none", and that it should be deleted without replacement. It seems there's:
* Wiki: no mention of rmtrans
* main Git repo: only the brief paragraph in the tools readme
* resources repo: no mention of it
* forums: only as part of a general list of Python files
* Github issues and PRs: only as part of a general list of Python files

FWIW, I think it's already possible to do with Gimp's default tools ("Colors", "Curves ...", select channel "Alpha", select curve type "Freehand", click in the bottom-left of the box and sweep down, then to the left edge of the box, then as far right as required).
