### PR TITLE
On Boost: update build scripts and documentation.

### PR DESCRIPTION
**Pull request by galegosimpatico**
At branch 'doc-from-discord-boost-discussion-20170926'.

The build documentation and scripts were slightly out of date about
Boost. This commit makes an interim update to them.

(CMakeLists.txt|SConstruct): `wesnoth` won't build using Boost lesser
than '1.50.0'. Boost 1.50.0 changed the location of version 3 of Boost
filesystem, from 'boost/filesystem/v3/' (e.g. for
'using boost::filesystem::v3::path;') to 'boost/filesystem/' (e.g. for
'using boost::filesystem::path;', enforced since the very introduction
of 'src/filesystem_boost.cpp'), making it incompatible unless using
precompiler directives for supporting backwards versions of Boost
filesystem prior than '1.50.0'. Using Boost 1.50.0 builds, but
segfaults on start up (in my mileage) (Valgrind hints about
'boost::detail::sp_counted_base'). I have not yet checked any more
than a single mileage, so I am not completely sure 1.50.0 is to be
discarded. In my mileage using Boost 1.51.0 makes the game boot and
saves able to load normally.

(INSTALL|projectfiles/VC12/README).md: Requirement of Boost libraries
 up to date.

.gitignore: Add KDevelop backup documents.

### CODE REVIEW

**Comment by galegosimpatico** [comment]
Tried to double check Boost 1.50.0 from a host I have with deb9 installed.

But I see no straightforward way of building Boost Locale from 1.50.0 (included) to 1.52.0 (included) on deb9, unlike in deb7.

    libs/locale/src/icu/formatter.cpp: In member function ‘virtual boost::locale::impl_icu::number_format<CharType>::string_type boost::locale::impl_icu::number_format<CharType>::format(boost::int64_t, size_t&) const’:
    libs/locale/src/icu/formatter.cpp:61:43: error: call of overloaded ‘format(boost::int64_t&, icu_57::UnicodeString&)’ is ambiguous
                     icu_fmt_->format(value,tmp);
                                               ^                                 
    In file included from libs/locale/src/icu/formatter.cpp:15:0:
    /usr/include/unicode/numfmt.h:318:20: note: candidate: icu_57::UnicodeString& icu_57::NumberFormat::format(double, icu_57::UnicodeString&) const
         UnicodeString& format(  double number,                  
                        ^~~~~~                           
    /usr/include/unicode/numfmt.h:331:20: note: candidate: icu_57::UnicodeString& icu_57::NumberFormat::format(int32_t, icu_57::UnicodeString&) const
         UnicodeString& format(  int32_t number,            
                        ^~~~~~                             
    /usr/include/unicode/numfmt.h:344:20: note: candidate: icu_57::UnicodeString& icu_57::NumberFormat::format(int64_t, icu_57::UnicodeString&) const
         UnicodeString& format(  int64_t number,               
                        ^~~~~~

The host where I run deb9 has deb8 in a different partition, so will check that another day.

**Comment by galegosimpatico** [comment]
Same result from deb8. Will likely not try Boost 1.50.0 in any other environment.

The bad part is I wasn't able to double check Boost 1.51.0 in a second host either.

**Comment by sevu** [comment]
Do I understand you correctly that you can't build with boost 1.50? 
It could be that the minimum boost version is higher than stated in the documentation, at least, for some reason the archlinux pkgbuild demands 1.60. Though, I wouldn't be surprised if this is a leftover from a already fixed issue.

**Comment by galegosimpatico** [comment]
> [...] for some reason the archlinux pkgbuild demands 1.60. [...]

Not knowledgeable on Arch here, but could that be because of it trying to avoid conflicts with anything else? Would that be a general purpose dev host? is a clean host such as a dedicated or maybe Travis CI?

I just found Boost 1.59.0 builds in deb9 (all chrono, filesystem, iostreams, locale, program_options, random, regex, system, thread) so it is very likely a build of master `wesnoth` can demonstrate Boost 1.59.0 is OK to master `wesnoth` (on deb9 (whose `apt` ships 1.62.0 anyway)), given I was able to build and run OK using 1.51.0 on deb7 (whose `apt` ships 1.49.0). But will check and follow up that.

But if I wanted `wesnoth` to build in deb9 and use `/usr/lib/` and no `/usr/local/lib/`, I would need to try to stick to '1.62.0'. I am trying to separate what the code requires (the object of the PR) and what each distro level requires, which doesn't belong to the generic list of requirements.

**Comment by galegosimpatico** [comment]
I can build and boot `wesnoth` on Debian Stretch (deb9) linking in run time Boost 1.59.0 (injected from `/usr/local/lib/`) instead of using the vanilla Boost 1.62.0 living in `/usr/lib/`.

Since Debian Jessie (deb8, released mid 2015) ships Boost 1.55.0, can most probably build master `wesnoth` with the vanilla Boost libs of that distro (can prove it if this were to be demanded), there is no case to state in `INSTALL.md` such high as 1.60 just because an Arch environment is requiring a 1.60 level of Boost :slightly_smiling_face:.

**Comment by Pentarctagon** [comment]
@sevu I have been building Wesnoth with Boost 1.58 on Mint 18.x successfully for a while, so the 1.60 requirement is probably an Arch thing.

@galegosimpatico It looks like this raises the minimum Boost version to 1.50, but you got a segfault with that version while 1.51 worked completely?  I would say it makes more sense to just put the minimum version as 1.51 then, since "it builds but makes a broken executable" seems not really a correct definition for a minimum required version.

**Comment by galegosimpatico** [comment]
@Pentarctagon could be, most probably. I just didn't want to put complete faith in a single host, specially given it's slightly [FrankenDebian](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian) because of reaching GCC's C++11 through a manual install of `4.8.4`.

I thought the final decision on that did not belong to me, but to the maintainer, until I could be sure of it using an alternative and (when possible) modern host, but later I got slammed by Boost `<=1.52.0` `locale` not compiling in `deb9` (nor even in `deb8`) the straightforward way I was expecting it would behave.

My last bullet now is to try to build `wesnoth` on Boost 1.50.0 on [steam-runtime](http://github.com/ValveSoftware/steam-runtime/).

**Comment by galegosimpatico** [comment]
As stated, `wesnoth` can be built using either Boost `1.50.0` or `1.51.0` (not `1.48.0` nor `1.49.0` anymore).

In my host with `deb7` (Wheezy), if using Boost `1.51.0` runs OK, if using Boost `1.50.0` crashes while booting up.

But when running [`steam-runtime`](https://github.com/ValveSoftware/steam-runtime/) on the same `deb7` on this same host, those old versions of Boost are straightforward to get compiled, so in this host I built `wesnoth` with each Boost version and running `steam-runtime` and both versions behaved the same one like the other. That behavior was buggy in both cases, but execution got that far I now suspect you shouldn't discard Boost `1.50.0` as a possible dependency version until you effectively use new facilities it introduces in later versions.

In a couple days I will have tried this same for `steam-runtime` environments on `deb8` (Jessie) and `deb9` (Stretch) I have in another host.

Next I will double check thoroughly if my host running `deb7` can't run `wesnoth` when built using Boost `1.50.0` to discard possible previous mistakes.

**Comment by galegosimpatico** [comment]
I don't know what might have had happened the other day. Today I was able to run `wesnoth` OK building on Boost `1.50.0`.

Checked using a `deb7` _Wheezy_ system enabled with C++11 by custom build and install of `gcc` `4.8.4`.

File: projectfiles/VC12/README.md [hunk 1]
```diff
@@ -82,7 +82,10 @@ folders, all version numbers are minimal requirements:
       into the 'lib' *General Folder*.
 
 
-   3. libboost-1.48.0 ( http://www.boost.org/ )
+   3. libboost-1.50.0 ( http://www.boost.org/ )
+
+      Note these instructions are still referring to Boost 1.48.0, and are so
```
Comment (jyrkive) [inline projectfiles/VC12/README.md]: The instructions are more severely outdated because of Wesnoth's dependencies themselves having changed...

Comment (galegosimpatico) [reply projectfiles/VC12/README.md]: Reject with "changes requested" then?

File: CMakeLists.txt [hunk 2]
```diff
@@ -75,7 +75,10 @@ else()
 endif()
 
 find_package(Crypto 1.0 REQUIRED)
-find_package(Boost 1.48 REQUIRED COMPONENTS iostreams program_options regex system thread random)
+find_package(
+	Boost 1.50 REQUIRED COMPONENTS
```
[the remark this answers is not in the document]
Comment (galegosimpatico) [reply CMakeLists.txt]: For me the best scenario would be to have the rest of changes accepted then unlocking PR to have someone else doing it, but if you find that PITA, would do.

**Comment by GregoryLundberg** [comment]
@galegosimpatico This PR only addresses CMake and does not address SCons or any other target or build system.

The title is that you're correcting the documentation, yet you're correcting several other things, such as the gitignore file and the actual build systems, but do not appear to be bringing the documentation up to match the actual current state of affairs.

File: projectfiles/VC12/README.md (hunk 1 above)
Comment (jyrkive) [reply projectfiles/VC12/README.md]: Well, instructions being outdated aren't really your fault, so it's not a valid reason to reject this PR.

File: CMakeLists.txt (hunk 2 above)
[the remark this answers is not in the document]
Comment (jyrkive) [reply CMakeLists.txt]: The most important thing is consistency. The same file should either be wrapped to 80/100/however many characters it uses, or not wrapped at all. Not wrapped in some lines and not others.

Personally I'm not interested in line length changes. When I add new code, I just follow the line length of the rest of the file.

File: projectfiles/VC12/README.md (hunk 1 above)
Comment (galegosimpatico) [reply projectfiles/VC12/README.md]: I assumed, wrongly, everything was OK, and mindlessly `grep`ed and replaced without even reading the files.

As it was already pointed out, the title of the PR is misleading (actually both commits too, for the same reason). I find that valid enough for rejection. These are all what I think we could do about this, bear in mind I'm noob at code review:

* Roll it back: close, either by unacceptable (misleading wording) or if anyone else is already taking care of or, broadly speaking, somehow assigned to it. Or even because of not actually meaningful enough, e.g.: project is planning to upgrade its Boost level in a shortest enough time.

* Roll it forward: stack commits, at least another one, until PR is acceptable. But since I don't generally care about Microsoft, somebody, rather than me, would have to state a target scope that I will take, or will not. In case of not taking, I assume the right thing is to unlock the PR for you to be free to use it only in case that seems useful or appropriate to you.

* Roll it over itself: squash and rebase until have something semantic and beautiful enough to be undoubtedly acceptable for merging. But I'm noob at this GitHub peer review system. I don't know how good it deals with rebase interactive followed by forced push to feature branch. The externally defined target scope thing introduced by the previous bullet still applies this.

* Simply accept it: If someone else is already somehow assigned to Microsoft-related documentation, and s/he loves it, maybe there is no point in asking me to deal with it.

Your call.

Comment (jyrkive) [reply projectfiles/VC12/README.md]: "Simply accept it" is what I prefer. I don't like increasing the scope of a pull request. I'm willing to merge any PR that is an improvement regardless of what related changes would be useful.

Regarding "roll it over itself", it works perfectly. I often use history rewriting and force pushes in my own pull requests. So don't worry about it breaking GitHub. (But be wary of the risk that by rewriting history you may accidentally erase changes which haven't been merged.)

Comment (GregoryLundberg) [reply projectfiles/VC12/README.md]: If you are using a branch on private fork you can 'roll over' the PR. For that, I use git rebase, usually with --interactive. It allows me to re-order the commits, merge commits, delete or add. When I have everything looking right I `git push -f` over my private fork branch and github figures it out,

Comment (jyrkive) [reply projectfiles/VC12/README.md]: Well, I rewrite history even in this upstream repository. :D (Although obviously not in master.)

**Comment by jyrkive** [comment]
All right. merged.

**Comment by galegosimpatico** [comment]
mai mam paras
