### ISSUE TITLE
wesnoth -m broken

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4472]
If I run `./wesnoth -m`, I get `error engine/team_construction: game_error: unknown unit type: Random` on stderr twice and a defeat dialog. Caused by 942a1d3d6df529267770c13c4e882f438e2dbcf7.

Tested in master, and marked as a 1.15.2 blocker, but it probably blocks 1.14.10 too.

**Comment by stevecotton** [comment]
The C++ unit tests have also broken, looks likely to be the same root cause:
```
src/tests/test_mp_connect.cpp(198): error: in "mp_connect/flg_map_settings": check side_engine->flg().current_leader() == "random" has failed [Random != random]
src/tests/test_mp_connect.cpp(212): error: in "mp_connect/flg_map_settings": check side_engine->flg().current_leader() == "random" has failed [Random != random]
src/tests/test_mp_connect.cpp(291): error: in "mp_connect/flg_map_settings": check side_engine->flg().current_gender() != "random" && side_engine->flg().current_gender() != "null" has failed
```

**Comment by Wedge009** [comment]
What is `wesnoth -m` supposed to do?

**Comment by Wedge009** [comment]
I suspect the problem is having too many things ride on the plain string "random" - it's used as a text label, but it's also used as a category.
